### ISSUE TITLE
BSD Licensing

### ISSUE THREAD

**Issue by djanatyn** [sontek/snowmachine#11]
Hi! I was curious about the licensing of this repository. I saw that there were some references to BSD in `setup.py`:
```
$ rg 'BSD' -C 2 setup.py
21-    description=("A python script that will make your terminal "
22-                 "snow"),
23:    license = "BSD",
24-    setup_requires=['setuptools-git'],
25-    install_requires=requires,
--
34-        "Environment :: Console",
35-        "Environment :: Console :: Curses",
36:        "License :: OSI Approved :: BSD License",
37-    ],
38-    entry_points = {

```

However, I didn't see a BSD license included within the repository or mentioned on the frontpage.

Would you consider including a copy of the BSD license (or any other license you'd like to use) within the repository?

**Comment by sontek** [comment]
Yeah, I'm definitely willing to include one.

**Comment by sontek** [comment]
done.  `LICENSE.txt` exists now as well as github showing what the license is

**Comment by djanatyn** [comment]
Thank you!
